[package]
name = "simulator"
version = "0.1.0"
authors = ["Anthony Wharton <a.wharton.2015@bristol.ac.uk>"]

[dependencies]
byteorder = "1.2.6"
elf       = "0.0.10"
tui       = "0.3.0-beta.3"
termion   = "1.5"
